// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9f7EVZrisE-Kf96hwooJgAv1OtqCTls',
    appId: '1:1090390887405:web:dfa971cff8f168a4d9b5e4',
    messagingSenderId: '1090390887405',
    projectId: 'mannergamer-c2546',
    authDomain: 'mannergamer-c2546.firebaseapp.com',
    storageBucket: 'mannergamer-c2546.appspot.com',
    measurementId: 'G-WHS4FB278Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh0EZOx44fQxm_a-VBqDabtvP0qH16Vuk',
    appId: '1:1090390887405:android:425089d55f409499d9b5e4',
    messagingSenderId: '1090390887405',
    projectId: 'mannergamer-c2546',
    storageBucket: 'mannergamer-c2546.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm5PWhthwwCDjOrL2ICzinf5WIMQN4-aQ',
    appId: '1:1090390887405:ios:c3b3b740ff1f564fd9b5e4',
    messagingSenderId: '1090390887405',
    projectId: 'mannergamer-c2546',
    storageBucket: 'mannergamer-c2546.appspot.com',
    iosClientId:
        '1090390887405-v3e2ttc6bvm7m9b4dvfdnbakhq4uhjba.apps.googleusercontent.com',
    iosBundleId: 'com.mannergamer.mannergamer',
  );
}
